### ISSUE TITLE
Runtime dependencies outdated

### ISSUE THREAD

**Issue by adetoola** [modosc/redux-persist-memory-storage#3]
I installed `redux-persist-memory-storage` in a react project, however, I get the following error whenever I try calling the module.
```
Error: Cannot find module '@babel/runtime/core-js/object/keys'
at Module._resolveFilename in core module.js — line 548
at Module._load in core module.js — line 475
at Module.require in core module.js — line 597
at require in core internal/module.js — line 11
 in redux-persist-memory-storage/lib/index.js — line 10
```
Environment
Node: 10.6.0
create-react-app: 1.5.2
Redux-persist: 5,
yarn : 1.9.4

Test Repo
Go to [npm runkit](https://npm.runkit.com/redux-persist-memory-storage) and click the run button. You will get the same error as above.

**Comment by modosc** [comment]
the only runtime dep is `@babel/runtime` - i updated everything to the most recent versions but afaik without `@babel/runtime` included in your project as well the code won't work.
