### ISSUE TITLE
invalid option passed to persistStore: "storage".

### ISSUE THREAD

**Issue by ukch** [modosc/redux-persist-memory-storage#4]
When following the usage instructions from the readme, I receive this error:

```
redux-persist: invalid option passed to persistStore: "storage". You may be incorrectly passing persistConfig into persistStore, whereas it should be passed into persistReducer.
```

Does this mean the docs are out of date?

**Comment by modosc** [comment]
i can't reproduce this, please reopen with more info if you're still running into issues. thanks!
